name: Test, build and release

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ffmpeg
        run: |
          sudo apt-get install -y ffmpeg

      - name: Install pypa/build
        run: |
          python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --wheel --outdir dist/ .

      - name: Install package
        run: |
          python -m pip install 'pycord[dev]' --find-links dist

      - name: Run tests
        run: |
          pytest --cov=pycord tests/

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
